### ISSUE TITLE
Suggestion: Secure a little bit The API Remote

### ISSUE THREAD

**Issue by shdf2** [FOR-PARADOX/Reboot#1]
Hello,
would it be possible to secure a little bit the API Remote ?
Actualy if you remove access to someone, he still has access to the configs untill he close OB...if he never close it he will have unlimited access. So maybe add a periodic "Config Rescan" every 30 minutes or something like that.
I asked Ruri about that and he doesn't want to do it.

Additionaly, anyone who know the API key can download all your LOLI files with a simple request with the API key in the authorization Header.... would it be possible to do something against that ??

**Comment by FOR-PARADOX** [comment]
That's a good idea. I haven't messed with the API at all yet. It may be worth looking into in the future.
