### ISSUE TITLE
FUNCTION broken on 1.2.6

### ISSUE THREAD

**Issue by Xero92** [FOR-PARADOX/Reboot#2]
After updating from 1.2.5 to 1.2.6 the function is not working properly.

1.2.5
Executed function UnixTimeToDate on input 1559858399 with outcome 6/6/2019
Parsed variable | Name: Expire Date | Value: 6/6/2019

1.2.6
Executed function UnixTimeToDate on input 1559858399 with outcome 6/6/2019

It does not actually save the variable value neither does it work as capture.

**Comment by FOR-PARADOX** [comment]
Fixed in 1.2.6.1
